export const FIXTURE_LIST_REQUEST = "FIXTURE_LIST_REQUEST";
export const FIXTURE_LIST_SUCCESS = "FIXTURE_LIST_SUCCESS";
export const FIXTURE_LIST_FAIL = "FIXTURE_LIST_FAIL";

export const FIXTURE_DETAILS_REQUEST = "FIXTURE_DETAILS_REQUEST";
export const FIXTURE_DETAILS_SUCCESS = "FIXTURE_DETAILS_SUCCESS";
export const FIXTURE_DETAILS_FAIL = "FIXTURE_DETAILS_FAIL";

export const FIXTURE_CREATE_REQUEST = "FIXTURE_CREATE_REQUEST";
export const FIXTURE_CREATE_SUCCESS = "FIXTURE_CREATE_SUCCESS";
export const FIXTURE_CREATE_FAIL = "FIXTURE_CREATE_FAIL";

export const FIXTURE_UPDATE_REQUEST = "FIXTURE_UPDATE_REQUEST";
export const FIXTURE_UPDATE_SUCCESS = "FIXTURE_UPDATE_SUCCESS";
export const FIXTURE_UPDATE_FAIL = "FIXTURE_UPDATE_FAIL";
