export const LEAGUE_ROW_CREATE_REQUEST = "LEAGUE_ROW_CREATE_REQUEST";
export const LEAGUE_ROW_CREATE_SUCCESS = "LEAGUE_ROW_CREATE_SUCCESS";
export const LEAGUE_ROW_CREATE_FAIL = "LEAGUE_ROW_CREATE_FAIL";

export const LEAGUE_ROW_REMOVE = "LEAGUE_ROW_REMOVE";
