export const PLAYER_LIST_REQUEST = "PLAYER_LIST_REQUEST";
export const PLAYER_LIST_SUCCESS = "PLAYER_LIST_SUCCESS";
export const PLAYER_LIST_FAIL = "PLAYER_LIST_FAIL";

export const PLAYER_DETAILS_REQUEST = "PLAYER_DETAILS_REQUEST";
export const PLAYER_DETAILS_SUCCESS = "PLAYER_DETAILS_SUCCESS";
export const PLAYER_DETAILS_FAIL = "PLAYER_DETAILS_FAIL";

export const PLAYER_LOGIN_REQUEST = "PLAYER_LOGIN_REQUEST";
export const PLAYER_LOGIN_SUCCESS = "PLAYER_LOGIN_SUCCESS";
export const PLAYER_LOGIN_FAIL = "PLAYER_LOGIN_FAIL";

export const PLAYER_LOGOUT = "PLAYER_LOGOUT";

export const PLAYER_REGISTER_REQUEST = "PLAYER_REGISTER_REQUEST";
export const PLAYER_REGISTER_SUCCESS = "PLAYER_REGISTER_SUCCESS";
export const PLAYER_REGISTER_FAIL = "PLAYER_REGISTER_FAIL";

export const PLAYER_UPDATE_REQUEST = "PLAYER_UPDATE_REQUEST";
export const PLAYER_UPDATE_SUCCESS = "PLAYER_UPDATE_SUCCESS";
export const PLAYER_UPDATE_FAIL = "PLAYER_UPDATE_FAIL";

export const PLAYER_PROFILE_REQUEST = "PLAYER_PROFILE_REQUEST";
export const PLAYER_PROFILE_SUCCESS = "PLAYER_PROFILE_SUCCESS";
export const PLAYER_PROFILE_FAIL = "PLAYER_PROFILE_FAIL";
