export const STAT_CREATE_REQUEST = "STAT_CREATE_REQUEST";
export const STAT_CREATE_SUCCESS = "STAT_CREATE_SUCCESS";
export const STAT_CREATE_FAIL = "STAT_CREATE_FAIL";

export const STAT_DELETE_REQUEST = "STAT_DELETE_REQUEST";
export const STAT_DELETE_SUCCESS = "STAT_DELETE_SUCCESS";
export const STAT_DELETE_FAIL = "STAT_DELETE_FAIL";
