const fixtures = [
  {
    _id: "1",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "Apple",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: true,
  },
  {
    _id: "2",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "GCC FC",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: false,
  },
  {
    _id: "3",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "Cannon",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: false,
  },
  {
    _id: "4",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "Sony",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: false,
  },
  {
    _id: "5",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "Logitech",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: false,
  },
  {
    _id: "6",
    venue: "Oval",
    league: "Thursday 7's Premier League",
    homeTeam: "Mates/Lads FC",
    awayTeam: "Amazon",
    homeGoals: 3,
    awayGoals: 1,
    isPlayed: false,
  },
];

export default fixtures;
