const fixtures = [
  {
    _id: "1",
    firstName: "Jack",
    lastName: "Keene",
    Team: "Mates/Lads FC",
    Appearances: 4,
    Goals: 3,
    Position: "Defender",
    cleanSheets: 3,
  },
  {
    _id: "2",
    firstName: "Test",
    lastName: "One",
    Team: "Mates/Lads FC",
    Appearances: 4,
    Goals: 3,
    Position: "Attacker",
    cleanSheets: 1,
  },
  {
    _id: "3",
    firstName: "Test",
    lastName: "Two",
    Team: "Mates/Lads FC",
    Appearances: 9,
    Goals: 3,
    Position: "Goalkeeper",
    cleanSheets: 6,
  },
  {
    _id: "4",
    firstName: "Test",
    lastName: "Three",
    Team: "Mates/Lads FC",
    Appearances: 4,
    Goals: 3,
    Position: "Defender",
    cleanSheets: 5,
  },
  {
    _id: "5",
    firstName: "Test",
    lastName: "Four",
    Team: "Mates/Lads FC",
    Appearances: 1,
    Goals: 3,
    Position: "Attacker",
    cleanSheets: 3,
  },
  {
    _id: "6",
    firstName: "Test",
    lastName: "Five",
    Team: "Mates/Lads FC",
    Appearances: 8,
    Goals: 3,
    Position: "Midfielder",
    cleanSheets: 2,
  },
];

export default fixtures;
